# https://taskfile.dev

version: '3'

vars:
  COLLECTION: -collection:pegasus=./lib

tasks:
  run:
    cmds:
      - odin run lib {{.CLI_ARGS}} -out:bin/pegasus
    sources:
      - ./lib/**/*.odin
    generates:
      - ./bin/pegasus
    aliases:
      - r
  build:
    cmds:
      - mkdir -p bin
      - odin build lib -o:speed -out:bin/pegasus
    sources:
      - ./lib/**/*.odin
    generates:
      - ./bin/pegasus
    aliases:
      - b
  test:
    cmds:
      - odin test {{.CLI_ARGS}} {{.COLLECTION}}
    aliases:
      - t
    silent: true
  clean:
    cmds:
      - rm -rf ./bin
    aliases:
      - c
    silent: true
  default:
    cmds:
      - task: run
    silent: true
