# https://taskfile.dev

version: '3'

vars:
  ODIN: odin
  COLLECTION: -collection:pegasus=./lib
  OUT: bin/pegasus

tasks:
  run:
    desc: Build and run the parser
    cmds:
      - mkdir -p bin
      - '{{.ODIN}} run lib {{.COLLECTION}} {{.CLI_ARGS}} -out:{{.OUT}}'
    sources:
      - ./lib/**/*.odin
    aliases:
      - r

  build:
    desc: Build optimized binary
    cmds:
      - mkdir -p bin
      - '{{.ODIN}} build lib {{.COLLECTION}} -o:speed -out:{{.OUT}}'
    sources:
      - ./lib/**/*.odin
    generates:
      - ./{{.OUT}}
    aliases:
      - b

  test:
    desc: "Run tests (usage: task test, task test -- lib/charset)"
    cmds:
      - '{{.ODIN}} test {{.CLI_ARGS | default "lib"}} {{.COLLECTION}}'
    aliases:
      - t

  test:all:
    desc: Run all test suites
    cmds:
      - '{{.ODIN}} test lib {{.COLLECTION}}'
      - '{{.ODIN}} test lib/charset {{.COLLECTION}}'
      - '{{.ODIN}} test lib/input {{.COLLECTION}}'
      - '{{.ODIN}} test lib/memo {{.COLLECTION}}'
    aliases:
      - ta

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf ./bin
    aliases:
      - c

  default:
    desc: Build and run (default task)
    cmds:
      - task: run
